version: "2"
checks:
  complex-logic:
    config:
      threshold: 12
  file-lines:
    config:
      threshold: 325
  method-complexity:
    config:
      threshold: 12
  method-lines:
    config:
      threshold: 50
  method-count:
    config:
      threshold: 30

plugins:
  fixme:
    enabled: true
  rubocop:
    enabled: true
