apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-www
spec:
  volumeName: pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ruby-tracer-ci-pipeline-run
spec:
  timeouts:
    pipeline: "2h"
  params:
  - name: revision
    value: "currency-add-new-pipeline"
  pipelineRef:
    name: ruby-tracer-currency-pipeline
  workspaces:
  - name: ruby-tracer-currency-pipeline-pvc
    persistentVolumeClaim:
        claimName: pvc-www
