apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ruby-tracer-ci-pipeline
spec:
  params:
  - name: revision
    type: string
  - name: ruby_31_image_digest
    type: string
    # ruby-3.1
    default: "public.ecr.aws/docker/library/ruby:3.1"
  - name: ruby_32_image_digest
    type: string
    # ruby-3.2
    default: "public.ecr.aws/docker/library/ruby:3.2"
  - name: ruby_33_image_digest
    type: string
    # ruby-3.3
    default: "public.ecr.aws/docker/library/ruby:3.3"
  - name: ruby_34_image_digest
    type: string
    # ruby-3.4
    default: "public.ecr.aws/docker/library/ruby:3.4"
  workspaces:
    - name: ruby-tracer-ci-pipeline-pvc
  tasks:
    - name: clone
      params:
      - name: revision
        value: $(params.revision)
      taskRef:
        name: ruby-tracer-clone-task
      workspaces:
        - name: task-pvc
          workspace: ruby-tracer-ci-pipeline-pvc
    - name: lint
      runAfter:
        - clone
      matrix:
        params:
          - name: imageDigest
            value:
            - $(params.ruby_33_image_digest)
          - name: gemfile
            value:
            - "gemfiles/rubocop_162.gemfile"
          - name: configuration
            value:
            - "lint"
      taskRef:
        name: ruby-tracer-unittest-default-libraries-task
      workspaces:
        - name: task-pvc
          workspace: ruby-tracer-ci-pipeline-pvc
    - name: core
      runAfter:
        - lint
      matrix:
        params:
          - name: imageDigest
            value:
            - $(params.ruby_31_image_digest)
            - $(params.ruby_32_image_digest)
            - $(params.ruby_33_image_digest)
            - $(params.ruby_34_image_digest)
          - name: gemfile
            value:
            - "./Gemfile"
          - name: configuration
            value:
            - "core"
      taskRef:
        name: ruby-tracer-unittest-default-libraries-task
      workspaces:
        - name: task-pvc
          workspace: ruby-tracer-ci-pipeline-pvc
    - name: unittest-default-ruby-31
      runAfter:
        - lint
        - core
      matrix:
        params:
          - name: imageDigest
            value:
            - $(params.ruby_31_image_digest)
          - name: gemfile
            value:
            - "./gemfiles/cuba_30.gemfile"
            - "./gemfiles/cuba_40.gemfile"
            - "./gemfiles/excon_079.gemfile"
            - "./gemfiles/excon_0100.gemfile"
            - "./gemfiles/excon_100.gemfile"
            - "./gemfiles/graphql_10.gemfile"
            - "./gemfiles/graphql_20.gemfile"
            - "./gemfiles/grpc_10.gemfile"
            - "./gemfiles/net_http_01.gemfile"
            - "./gemfiles/rack_20.gemfile"
            - "./gemfiles/rack_30.gemfile"
            - "./gemfiles/rest_client_20.gemfile"
            - "./gemfiles/roda_20.gemfile"
            - "./gemfiles/roda_30.gemfile"
            - "./gemfiles/sinatra_22.gemfile"
            - "./gemfiles/sinatra_30.gemfile"
            - "./gemfiles/sinatra_40.gemfile"
            - "./gemfiles/shoryuken_50.gemfile"
            - "./gemfiles/shoryuken_60.gemfile"
          - name: configuration
            value:
            - "libraries"
      taskRef:
        name: ruby-tracer-unittest-default-libraries-task
      workspaces:
        - name: task-pvc
          workspace: ruby-tracer-ci-pipeline-pvc
    - name: unittest-default-ruby-32
      runAfter:
        - unittest-default-ruby-31
      matrix:
        params:
          - name: imageDigest
            value:
            - $(params.ruby_32_image_digest)
          - name: gemfile
            value:
            - "./gemfiles/cuba_30.gemfile"
            - "./gemfiles/cuba_40.gemfile"
            - "./gemfiles/excon_079.gemfile"
            - "./gemfiles/excon_0100.gemfile"
            - "./gemfiles/excon_100.gemfile"
            - "./gemfiles/graphql_10.gemfile"
            - "./gemfiles/graphql_20.gemfile"
            - "./gemfiles/grpc_10.gemfile"
            - "./gemfiles/net_http_01.gemfile"
            - "./gemfiles/rack_20.gemfile"
            - "./gemfiles/rack_30.gemfile"
            - "./gemfiles/rest_client_20.gemfile"
            - "./gemfiles/roda_20.gemfile"
            - "./gemfiles/roda_30.gemfile"
            - "./gemfiles/sinatra_22.gemfile"
            - "./gemfiles/sinatra_30.gemfile"
            - "./gemfiles/sinatra_40.gemfile"
            - "./gemfiles/shoryuken_50.gemfile"
            - "./gemfiles/shoryuken_60.gemfile"
          - name: configuration
            value:
            - "libraries"
      taskRef:
        name: ruby-tracer-unittest-default-libraries-task
      workspaces:
        - name: task-pvc
          workspace: ruby-tracer-ci-pipeline-pvc
    - name: unittest-default-ruby-33
      runAfter:
        - unittest-default-ruby-32
      matrix:
        params:
          - name: imageDigest
            value:
            - $(params.ruby_33_image_digest)
          - name: gemfile
            value:
            - "./gemfiles/cuba_30.gemfile"
            - "./gemfiles/cuba_40.gemfile"
            - "./gemfiles/excon_079.gemfile"
            - "./gemfiles/excon_0100.gemfile"
            - "./gemfiles/excon_100.gemfile"
            - "./gemfiles/graphql_10.gemfile"
            - "./gemfiles/graphql_20.gemfile"
            - "./gemfiles/grpc_10.gemfile"
            - "./gemfiles/net_http_01.gemfile"
            - "./gemfiles/rack_20.gemfile"
            - "./gemfiles/rack_30.gemfile"
            - "./gemfiles/rest_client_20.gemfile"
            - "./gemfiles/roda_20.gemfile"
            - "./gemfiles/roda_30.gemfile"
            - "./gemfiles/sinatra_22.gemfile"
            - "./gemfiles/sinatra_30.gemfile"
            - "./gemfiles/sinatra_40.gemfile"
            - "./gemfiles/shoryuken_50.gemfile"
            - "./gemfiles/shoryuken_60.gemfile"
          - name: configuration
            value:
            - "libraries"
      taskRef:
        name: ruby-tracer-unittest-default-libraries-task
      workspaces:
        - name: task-pvc
          workspace: ruby-tracer-ci-pipeline-pvc
    - name: unittest-default-ruby-34
      runAfter:
        - unittest-default-ruby-33
      matrix:
        params:
          - name: imageDigest
            value:
            - $(params.ruby_34_image_digest)
          - name: gemfile
            value:
            - "./gemfiles/cuba_30.gemfile"
            - "./gemfiles/cuba_40.gemfile"
            - "./gemfiles/excon_079.gemfile"
            - "./gemfiles/excon_0100.gemfile"
            - "./gemfiles/excon_100.gemfile"
            - "./gemfiles/graphql_10.gemfile"
            - "./gemfiles/graphql_20.gemfile"
            - "./gemfiles/grpc_10.gemfile"
            - "./gemfiles/net_http_01.gemfile"
            - "./gemfiles/rack_20.gemfile"
            - "./gemfiles/rack_30.gemfile"
            - "./gemfiles/rest_client_20.gemfile"
            - "./gemfiles/roda_20.gemfile"
            - "./gemfiles/roda_30.gemfile"
            - "./gemfiles/sinatra_22.gemfile"
            - "./gemfiles/sinatra_30.gemfile"
            - "./gemfiles/sinatra_40.gemfile"
            - "./gemfiles/shoryuken_50.gemfile"
            - "./gemfiles/shoryuken_60.gemfile"
          - name: configuration
            value:
            - "libraries"
      taskRef:
        name: ruby-tracer-unittest-default-libraries-task
      workspaces:
        - name: task-pvc
          workspace: ruby-tracer-ci-pipeline-pvc
    - name: unittest-mongo
      runAfter:
        - unittest-default-ruby-34
      matrix:
        params:
          - name: imageDigest
            value:
            - $(params.ruby_31_image_digest)
            - $(params.ruby_32_image_digest)
            - $(params.ruby_33_image_digest)
            - $(params.ruby_34_image_digest)
          - name: gemfile
            value:
            - "./gemfiles/mongo_216.gemfile"
            - "./gemfiles/mongo_219.gemfile"
      taskRef:
        name: ruby-tracer-unittest-mongo-libraries-task
      workspaces:
        - name: task-pvc
          workspace: ruby-tracer-ci-pipeline-pvc
    - name: unittest-memcached
      runAfter:
        - unittest-mongo
      matrix:
        params:
          - name: imageDigest
            value:
            - $(params.ruby_31_image_digest)
            - $(params.ruby_32_image_digest)
            - $(params.ruby_33_image_digest)
            - $(params.ruby_34_image_digest)
          - name: gemfile
            value:
            - "./gemfiles/dalli_20.gemfile"
            - "./gemfiles/dalli_30.gemfile"
            - "./gemfiles/dalli_32.gemfile"
      taskRef:
        name: ruby-tracer-unittest-memcached-libraries-task
      workspaces:
        - name: task-pvc
          workspace: ruby-tracer-ci-pipeline-pvc
    - name: unittest-aws
      runAfter:
        - unittest-memcached
      matrix:
        params:
          - name: imageDigest
            value:
            - $(params.ruby_31_image_digest)
            - $(params.ruby_32_image_digest)
            - $(params.ruby_33_image_digest)
            - $(params.ruby_34_image_digest)
          - name: gemfile
            value:
            - "./gemfiles/aws_30.gemfile"
            - "./gemfiles/aws_60.gemfile"
      taskRef:
        name: ruby-tracer-unittest-aws-libraries-task
      workspaces:
        - name: task-pvc
          workspace: ruby-tracer-ci-pipeline-pvc
    - name: unittest-redis-ruby-31
      runAfter:
        - unittest-aws
      matrix:
        params:
          - name: imageDigest
            value:
            - $(params.ruby_31_image_digest)
          - name: gemfile
            value:
            - "./gemfiles/redis_40.gemfile"
            - "./gemfiles/redis_50.gemfile"
            - "./gemfiles/redis_51.gemfile"
            - "./gemfiles/resque_122.gemfile"
            - "./gemfiles/resque_20.gemfile"
            - "./gemfiles/sidekiq_42.gemfile"
            - "./gemfiles/sidekiq_50.gemfile"
            - "./gemfiles/sidekiq_60.gemfile"
            - "./gemfiles/sidekiq_65.gemfile"
            - "./gemfiles/sidekiq_70.gemfile"
      taskRef:
        name: ruby-tracer-unittest-redis-libraries-task
      workspaces:
        - name: task-pvc
          workspace: ruby-tracer-ci-pipeline-pvc
    - name: unittest-redis-ruby-32-33
      runAfter:
        - unittest-redis-ruby-31
      matrix:
        params:
          - name: imageDigest
            value:
            - $(params.ruby_32_image_digest)
            - $(params.ruby_33_image_digest)
          - name: gemfile
            value:
            - "./gemfiles/redis_40.gemfile"
            - "./gemfiles/redis_50.gemfile"
            - "./gemfiles/redis_51.gemfile"
            - "./gemfiles/resque_122.gemfile"
            - "./gemfiles/resque_20.gemfile"
            - "./gemfiles/sidekiq_42.gemfile"
            - "./gemfiles/sidekiq_50.gemfile"
            - "./gemfiles/sidekiq_60.gemfile"
            - "./gemfiles/sidekiq_65.gemfile"
            - "./gemfiles/sidekiq_70.gemfile"
      taskRef:
        name: ruby-tracer-unittest-redis-libraries-task
      workspaces:
        - name: task-pvc
          workspace: ruby-tracer-ci-pipeline-pvc
    - name: unittest-redis-ruby-34
      runAfter:
        - unittest-redis-ruby-32-33
      matrix:
        params:
          - name: imageDigest
            value:
            - $(params.ruby_34_image_digest)
          - name: gemfile
            value:
            - "./gemfiles/redis_40.gemfile"
            - "./gemfiles/redis_50.gemfile"
            - "./gemfiles/redis_51.gemfile"
            - "./gemfiles/resque_122.gemfile"
            - "./gemfiles/resque_20.gemfile"
            - "./gemfiles/sidekiq_42.gemfile"
            - "./gemfiles/sidekiq_50.gemfile"
            - "./gemfiles/sidekiq_60.gemfile"
            - "./gemfiles/sidekiq_65.gemfile"
            - "./gemfiles/sidekiq_70.gemfile"
      taskRef:
        name: ruby-tracer-unittest-redis-libraries-task
      workspaces:
        - name: task-pvc
          workspace: ruby-tracer-ci-pipeline-pvc
    - name: unittest-rails-sqlite3
      runAfter:
        - unittest-redis-ruby-34
      matrix:
        params:
          - name: imageDigest
            value:
            - $(params.ruby_31_image_digest)
            - $(params.ruby_32_image_digest)
            - $(params.ruby_33_image_digest)
            - $(params.ruby_34_image_digest)
          - name: gemfile
            value:
            - "./gemfiles/rails_61.gemfile"
            - "./gemfiles/rails_70.gemfile"
            - "./gemfiles/rails_71.gemfile"
      taskRef:
        name: ruby-tracer-unittest-rails-sqlite3-task
      workspaces:
        - name: task-pvc
          workspace: ruby-tracer-ci-pipeline-pvc
    - name: unittest-rails-mysql2
      runAfter:
        - unittest-rails-sqlite3
      matrix:
        params:
          - name: imageDigest
            value:
            - $(params.ruby_31_image_digest)
            - $(params.ruby_32_image_digest)
            - $(params.ruby_33_image_digest)
            - $(params.ruby_34_image_digest)
          - name: gemfile
            value:
            - "./gemfiles/rails_61.gemfile"
            - "./gemfiles/rails_70.gemfile"
            - "./gemfiles/rails_71.gemfile"
      taskRef:
        name: ruby-tracer-unittest-rails-mysql2-task
      workspaces:
        - name: task-pvc
          workspace: ruby-tracer-ci-pipeline-pvc
    - name: unittest-rails-postgres
      runAfter:
        - unittest-rails-mysql2
      matrix:
        params:
          - name: imageDigest
            value:
            - $(params.ruby_31_image_digest)
            - $(params.ruby_32_image_digest)
            - $(params.ruby_33_image_digest)
            - $(params.ruby_34_image_digest)
          - name: gemfile
            value:
            - "./gemfiles/rails_61.gemfile"
            - "./gemfiles/rails_70.gemfile"
            - "./gemfiles/rails_71.gemfile"
      taskRef:
        name: ruby-tracer-unittest-rails-postgres-task
      workspaces:
        - name: task-pvc
          workspace: ruby-tracer-ci-pipeline-pvc
    - name: unittest-sequel-sqlite3
      runAfter:
        - unittest-rails-postgres
      matrix:
        params:
          - name: imageDigest
            value:
            - $(params.ruby_31_image_digest)
            - $(params.ruby_32_image_digest)
            - $(params.ruby_33_image_digest)
            - $(params.ruby_34_image_digest)
          - name: gemfile
            value:
            - "./gemfiles/sequel_56.gemfile"
            - "./gemfiles/sequel_57.gemfile"
            - "./gemfiles/sequel_58.gemfile"
      taskRef:
        name: ruby-tracer-unittest-sequel-sqlite3-task
      workspaces:
        - name: task-pvc
          workspace: ruby-tracer-ci-pipeline-pvc
    - name: unittest-sequel-mysql2
      runAfter:
        - unittest-sequel-sqlite3
      matrix:
        params:
          - name: imageDigest
            value:
            - $(params.ruby_31_image_digest)
            - $(params.ruby_32_image_digest)
            - $(params.ruby_33_image_digest)
            - $(params.ruby_34_image_digest)
          - name: gemfile
            value:
            - "./gemfiles/sequel_56.gemfile"
            - "./gemfiles/sequel_57.gemfile"
            - "./gemfiles/sequel_58.gemfile"
      taskRef:
        name: ruby-tracer-unittest-sequel-mysql2-task
      workspaces:
        - name: task-pvc
          workspace: ruby-tracer-ci-pipeline-pvc
    - name: generate-currency-report
      runAfter:
        - unittest-sequel-mysql2
      taskRef:
        name: ruby-generate-currency-report-task
      workspaces:
        - name: task-pvc
          workspace: ruby-tracer-ci-pipeline-pvc
    - name: upload-currency-report
      runAfter:
        - generate-currency-report
      taskRef:
        name: ruby-upload-currency-report-task
      workspaces:
        - name: task-pvc
          workspace: ruby-tracer-ci-pipeline-pvc
