---
# Service account which will be use to reset the daemonset,
kind: ServiceAccount
apiVersion: v1
metadata:
  name: prepuller-restart
---
# allow getting status and patching only the one daemonset you want
# to restart
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prepuller-restart
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["daemonsets"]
    resourceNames: ["ruby-tracer-prepuller"]
    verbs: ["get", "patch"]
---
# bind the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prepuller-restart
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prepuller-restart
subjects:
  - kind: ServiceAccount
    name: prepuller-restart
