apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ruby-tracer-prepuller
spec:
  selector:
    matchLabels:
      name: ruby-tracer-prepuller
  template:
    metadata:
      labels:
        name: ruby-tracer-prepuller
    spec:
      # Configure an init container for each image you want to pull
      initContainers:
        - name: prepuller-git
          # alpine/git:latest
          image: public.ecr.aws/docker/library/alpine:latest
          command: ["sh", "-c", "'true'"]
        - name: prepuller-dynamodb
          # amazon/dynamodb-local:2.3.0
          image: public.ecr.aws/aws-dynamodb-local/aws-dynamodb-local:2.3.0
          command: ["sh", "-c", "'true'"]
        - name: prepuller-s3
          # minio/minio
          image: quay.io/minio/minio
          command: ["sh", "-c", "'true'"]
        - name: prepuller-sns
          # s12v/sns:latest
          image: public.ecr.aws/redbox-public/s12v/sns:latest
          command: ["sh", "-c", "'true'"]
        - name: prepuller-sqs
          # sprig/elasticmq-native
          image: public.ecr.aws/sprig/elasticmq-native
          command: ["sh", "-c", "'true'"]
        - name: prepuller-memcached
          # memcached:1.6.24-bookworm
          image: public.ecr.aws/docker/library/memcached:1.6.24-bookworm
          command: ["sh", "-c", "'true'"]
        - name: prepuller-redis
          # redis:7.2.4-bookworm
          image: public.ecr.aws/docker/library/redis:7.2.4-bookworm
          command: ["sh", "-c", "'true'"]
        - name: prepuller-mongo
          # mongo:5-focal
          image: public.ecr.aws/docker/library/mongo:5-focal
          command: ["sh", "-c", "'true'"]
          imagePullPolicy: Always
        - name: prepuller-mariadb
          # mariadb:11.3.2
          image: public.ecr.aws/docker/library/mariadb:11.3.2
          command: ["sh", "-c", "'true'"]
        - name: prepuller-postgres
          # postgres:16.2-bookworm
          image: public.ecr.aws/docker/library/postgres:16.2-bookworm
          command: ["sh", "-c", "'true'"]
        - name: prepuller-31
          # ruby-3.1
          image: public.ecr.aws/docker/library/ruby:3.1
          command: ["sh", "-c", "'true'"]
          imagePullPolicy: Always
        - name: prepuller-32
          # ruby-3.2
          image: public.ecr.aws/docker/library/ruby:3.2
          command: ["sh", "-c", "'true'"]
          imagePullPolicy: Always
        - name: prepuller-33
          # ruby-3.3
          image: public.ecr.aws/docker/library/ruby:3.3
          command: ["sh", "-c", "'true'"]
          imagePullPolicy: Always
        - name: prepuller-34
          # ruby-3.4
          image: public.ecr.aws/docker/library/ruby:3.4
          command: ["sh", "-c", "'true'"]
          imagePullPolicy: Always
      # Use the pause container to ensure the Pod goes into a `Running` phase
      # but doesn't take up resource on the cluster
      containers:
        - name: pause
          image: gcr.io/google_containers/pause:3.2
          resources:
            limits:
              cpu: 1m
              memory: 8Mi
            requests:
              cpu: 1m
              memory: 8Mi
