apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ruby-currency-cron-listener
spec:
  serviceAccountName: tekton-triggers-eventlistener-serviceaccount
  triggers:
    - name: currency-cron-trigger
      template:
        ref: ruby-currency-trigger-template
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: ruby-currency-trigger-template
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: ruby-currency-
    spec:
      pipelineRef:
        name: ruby-currency-pipeline
      serviceAccountName: currency-serviceaccount
      params:
      - name: revision
        value: "master"
      workspaces:
      - name: ruby-currency-pvc
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Mi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ruby-currency-cronjob
spec:
  schedule: "5 3 * * Mon-Fri"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: http-request-to-el-svc
            # curlimages/curl:8.6.0
            image: curlimages/curl@sha256:f2237028bed58de91f62aea74260bb2a299cf12fbcabc23cfaf125fef276c884
            imagePullPolicy: IfNotPresent
            args: ["curl", "-X", "POST", "--data", "{}", "el-ruby-currency-cron-listener.default.svc.cluster.local:8080"]
          restartPolicy: OnFailure
---
