apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ruby-currency-pipelinerun
spec:
  params:
  - name: revision
    value: "currency-update"
  pipelineRef:
    name: ruby-currency-pipeline
  serviceAccountName: currency-serviceaccount
  workspaces:
  - name: ruby-currency-pvc
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
